config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]

  resources :events, only: %i[index new create show] do
    resources :event_attendances, only: %i[create]
  end

  resources :event_attendances, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :event_attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :event_attendances, source: :attendee

  validates :name, :event_date, presence: true

  delegate :name, to: :creator, prefix: true

  scope :past, -> { where('event_date < ?', Time.zone.now) }
  scope :upcoming, -> { where('event_date >= ?', Time.zone.now) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, dependent: :destroy

  has_many :event_attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :event_attendances, source: :attended_event

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }

  def upcoming_events
    attended_events.where('event_date >= ?', Time.zone.now)
  end

  def previous_events
    attended_events.where('event_date < ?', Time.zone.now)
  end

  def find_attended_event(event)
    event_attendances.find_by(attended_event_id: event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :error, :success

  include SessionsHelper

  protected

  def authenticate_user
    redirect_to root_path, error: 'Please login or sign up to continue' unless user_signed_in?
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :authenticate_user

  def create
    @event = Event.find(params[:event_id])
    @event_attendance = current_user.event_attendances.build(attended_event: @event)

    if @event.attendees.exists?(current_user.id)
      redirect_back fallback_location: root_path, error: 'You have already joined this event'
    else
      @event_attendance.save
      redirect_back fallback_location: root_path, success: 'You have joined this event'
    end
  end

  def destroy
    @event_attended = EventAttendance.find(params[:id])
    @event_attended.destroy

    redirect_back fallback_location: root_path, success: 'Removed from this event'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, only: %i[new create]

  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      EventAttendance.create! attendee: current_user, attended_event: @event
      redirect_to @event, success: 'You have been added to the events attendee list'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :event_date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render layout: 'slate'
  end

  def create
    @user = User.find_by(name: params[:name])

    if @user
      sign_in(@user)
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid name'
      render :new
    end
  end

  def destroy
    sign_out_user
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[show]

  def new
    @user = User.new

    render layout: 'slate'
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_path, success: 'Successfully created your account'
    else
      render :new
    end
  end

  def show
    @users_event = current_user.events
    @upcoming_events = current_user.upcoming_events
    @previous_events = current_user.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_events(event)
    if event.attendees.size.positive?
      render '/events/show_events', event: event
    else
      render '/events/no_events'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:auth_token] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: cookies[:auth_token]) if cookies[:auth_token]
  end

  def user_signed_in?
    current_user.present?
  end

  def sign_out_user
    cookies.delete(:auth_token) if user_signed_in?
  end
end

app/helpers/toast_helper.rb
module ToastHelper
  def toast_icon_for(status)
    case status
    when 'error'
      'stop'
    when 'success'
      'check'
    else
      raise "Undefined flash type: #{status}"
    end
  end
end

app/views/events/_event.html.erb
<p class="f4"><%= link_to event.name, event %> <span class="text-gray f5">on <%= event.event_date %></span></p>

app/views/events/_event_actionable.html.erb
<% if user_signed_in? %>
  <% if @event.attendees.exists?(current_user.id) %>
    <%= form_with url: event_attendance_path(current_user.find_attended_event(@event)), method: :delete do |form| %>
      <%= form.submit "Exit this event", class: "btn btn-danger" %>
    <% end %>
  <% else %>
    <%= form_with url: event_event_attendances_path(@event) do |form| %>
      <%= form.submit "Join this event", class: "btn btn-primary" %>
    <% end %>
  <% end %>
<% end %>

app/views/events/_no_events.html.erb
<p>Currently no one is attending this event</p>

app/views/events/_show_events.html.erb
<% event.attendees.each do |attendee| %>
          <p><%= attendee.name %></p>
        <% end %>

app/views/events/index.html.erb
<main class="d-flex flex-justify-center py-7">
  <div class="width-full mx-auto">
    <div class="Box width-full max-w-sm mx-auto">
      <div class="Box-body">
        <h3 class="mb-3">Upcoming events</h3>
        <%= render @upcoming_events %>
      </div>
    </div>
    <div class="Box width-full max-w-sm mx-auto mt-4">
      <div class="Box-body">
        <h3 class="mb-3">Past events</h3>
        <%= render @past_events %>
      </div>
    </div>
  </div>
</main>

app/views/events/new.html.erb
<main class="d-flex flex-justify-center min-h-screen bg-gray">
  <div class="max-w-sm width-full py-8">
    <h1 class="f2 text-center">Create an event</h1>
    <%= form_with model: @event, class: "mt-4 Box Box--spacious" do |form| %>
      <div class="Box-body">
        <div class="form-group mt-0">
          <div class="form-group-header">
            <%= form.label :name %>
          </div>
          <div class="form-group-body">
            <%= form.text_field :name, class: "form-control", autocomplete: "off", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="form-group-header">
            <%= form.label :event_date %>
          </div>
          <div class="form-group-body">
            <%= form.datetime_local_field :event_date, class: "form-control", autocomplete: "off" %>
          </div>
        </div>
        <div class="form-group">
          <div class="form-group-header">
            <%= form.label :description %>
          </div>
          <div class="form-group-body">
            <%= form.text_area :description, class: "form-control", autocomplete: "off" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.submit "Create event", class: "btn btn-primary btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/events/show.html.erb
<main class="d-flex flex-justify-center py-7">
  <div>
    <div>
      <h2><%= @event.name %></h2>
      <p>Created by <%= @event.creator_name %> on <%= @event.event_date %></p>
      <%= render "event_actionable" %>
    </div>
    <div class="mt-4" id="attendee-list">
      <h4>Attendees</h4>
      <%= show_events(@event) %>
    </div>
  </div>
</main>

app/views/flashes/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="position-fixed top-0 right-0 mb-3 ml-3" style="z-index: 99999999;">
    <div class="Toast Toast--<%= type %>">
      <span class="Toast-icon">
        <%= octicon toast_icon_for(type) %>
      </span>
      <span class="Toast-content"><%= msg %></span>
      <button type="button" class="Toast-dismissButton"><%= octicon "x" %></button>
    </div>
  </div>
<% end %>

app/views/headers/_default.html.erb
<div class="Header">
  <div class="Header-item mr-6">
    <%= link_to root_path, class: "Header-link f4 d-flex flex-items-center" do %>
      <%= octicon "mark-github", class: "mr-2", height: 32 %>
      <span>Private Events</span>
    <% end %>
  </div>
  <div class="Header-item">
    <%= link_to "All events", events_path, class: "Header-link" %>
  </div>
  <div class="Header-item Header-item--full">
    <%= link_to "New event", new_event_path, class: "Header-link" %>
  </div>
  <% if current_user %>
    <div class="Header-item mr-0">
      <details class="dropdown details-reset details-overlay d-inline-block">
        <summary aria-haspopup="true">
          <img class="avatar avatar-5 circle" alt="@octocat" src="https://github.com/octocat.png">
        </summary>
        <ul class="dropdown-menu dropdown-menu-sw">
          <li class="px-3 pb-2">
            <span class="d-block text-gray">Signed in as</span>
            <span class="d-block text-gray-dark h5"><%= current_user.name %></span>
          </li>
          <li><%= link_to "Your events", user_path(current_user), class: "dropdown-item" %></li>
          <li class="dropdown-divider"></li>
          <li><%= link_to "Sign out", session_path("current_user"), method: :delete, class: "dropdown-item" %></li>
        </ul>
      </details>
    </div>
  <% else %>
    <div class="Header-item">
      <%= link_to "Sign in", new_session_path, class: "Header-link" %>
    </div>
    <div class="Header-item">
      <%= link_to "Sign up", new_user_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "flashes/flash" %>
    <%= render "headers/default" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/slate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "flashes/flash" %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<main class="d-flex flex-justify-center min-h-screen bg-gray">
  <div class="max-w-sm width-full py-8">
    <h1 class="f2 text-center">Create an account to get started</h1>
    <%= form_with model: @user, class: "mt-4 Box Box--spacious" do |form| %>
      <div class="Box-body">
        <div class="form-group mt-0">
          <div class="form-group-header">
            <%= form.label :name %>
          </div>
          <div class="form-group-body">
            <%= form.text_field :name, class: "form-control", autocomplete: "off", autofocus: true %>
            <p class="mt-1 text-red h5"><%= @user.errors.full_messages_for(:name).first %></p>
          </div>
        </div>
        <div class="form-group">
          <%= form.submit "Sign up", class: "btn btn-primary btn-block" %>
        </div>
      </div>
    <% end %>
    <p class="text-center mt-4 text-gray">Already have an account? <%= link_to "Sign in", new_session_path %></p>
  </div>
</main>

app/views/users/show.html.erb
<main class="d-flex flex-justify-center py-7">
  <div class="width-full mx-auto">
    <div class="Box width-full max-w-sm mx-auto">
      <div class="Box-body">
        <h3 class="mb-3">Events created by you</h3>
        <%= render @users_event %>
      </div>
    </div>
    <div class="Box width-full max-w-sm mx-auto mt-4">
      <div class="Box-body">
        <h3 class="mb-3">Previously attended events by you</h3>
        <%= render @previous_events %>
      </div>
    </div>
    <div class="Box width-full max-w-sm mx-auto mt-4">
      <div class="Box-body">
        <h3 class="mb-3">Upcoming events for you</h3>
        <%= render @upcoming_events %>
      </div>
    </div>
  </div>
</main>